### ISSUE TITLE
"0 Active profiles indexed"

### ISSUE THREAD

**Issue by maxrob27** [jcontini/facebook-friends-map#20]
Hi, love the idea but i am having issues with it finding the data. I assume the error follows from no data found. Any idea as to why this could be the case/any recent changes? I have followed the instructions as far as I can tell.
![image](https://user-images.githubusercontent.com/44088162/82123861-9096a580-9793-11ea-854c-9aaa4bd39e44.png)

If this helps, this was a previous issue but (I think) may have been resolved with administrator privilleges.
![image](https://user-images.githubusercontent.com/44088162/82123881-ba4fcc80-9793-11ea-9e4f-2998c333ff8e.png)

Many thanks

**Comment by jcontini** [comment]
Hey @maxrob27 ! Thanks for flagging this, it looks like there was a bug where the script wouldn't check to see if profiles were downloaded first. It jumped to try and make a map anyway and so ran into an issue. I updated it so that it will try to re-index before mapping. Can you download the latest and try again?

**Comment by maxrob27** [comment]
Thanks for the quick reply. I have tried that and still no success. The current issue is now: "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 83
" but I am using chrome beta version 83 and I also tried to manually set paths.
`options = webdriver.ChromeOptions()`

`options.binary_location = "C:/Program Files (x86)/Google/Chrome Beta/Application/chrome.exe"`

`chrome_driver_binary = "C:/Users/{{{username}}}/AppData/Local/Programs/Python/Python37/Lib/site-packages/chromedriver_binary/chromedriver.exe"`

`driver = webdriver.Chrome(chrome_driver_binary, chrome_options=options)`

any thoughts? could this be rather an issue at my end now?

**Comment by jcontini** [comment]
Hmm that's strange. I just downloaded the latest Chrome beta and I'm unable to reproduce, though I'm on a mac. Can I ask you to try these 2 steps?

1. In the script directory, run `pipenv install` again, and then `pipenv update`
2. Just to double-confirm, try downloading the latest Chrome beta again: https://www.google.com/chrome/beta/

Let me know if that helps

**Comment by maxrob27** [comment]
I had the right beta but now used `pipenv update` so now it seems to be getting further, up until the point where it ends with the scrolling down. 
![image](https://user-images.githubusercontent.com/44088162/82586811-164d9300-9b90-11ea-99ce-1f6b9867533e.png)
Small note: you have to make sure there is no two factor authentication otherwise it definitely doesn't work! Thanks again for your help

**Comment by jcontini** [comment]
Glad we're making progress! I read up on this error and it seems that indeed it can be [a problem parsing special/foreign characters on Windows](https://stackoverflow.com/questions/27092833/unicodeencodeerror-charmap-codec-cant-encode-characters). I updated the code to specify encoding on each file save so that hopefully fixes it on Windows.

Can you pull the latest version and try again?

**Comment by maxrob27** [comment]
That seems to have done the trick! It hit the activity warning so I will have to wait a week or two to get the final result, hopefully no problems from now. Thank you again.

**Comment by jcontini** [comment]
Great! Yeah, facebook added the rate limits recently so I figured it was better to make the script behave nicely rather than risk anything. I don't know what a safe retry time is, eg an hour or a day, but I don't want to ask anyone to test it either haha.

If you'd like to see the map of what it's got so far, just run this (it doesn't need to log into facebook for this):
`python make.py --geocode --map`

Thanks again for your feedback! Please open another issue if you run into any more problems.
