### ISSUE TITLE
Empty Lists

### ISSUE THREAD

**Issue by maxrob27** [jcontini/facebook-friends-map#21]
Hi, sorry it's me again. I wonder if facebook recently changed a few things or if it's just me. The issue I now have is the map. It tries to create the map but has no locations to work with. I traced this back (I think) to 'details' as an empty list for each profile. I wonder if the XPath is different now or something along those lines?

The original line `profile_id = int(r.split('/')[-1].split('.')[0])` I had to alter to `profile_id = int(r.split('/')[-1].split('.')[0][11:])` in order for anything to work. Maybe that shouldn't be the case but it had issues with "profiles\\' at the start and trying to turn to an integer.

**Comment by jcontini** [comment]
Oh man you're right! It works great for profiles I downloaded from April 1 & before, but not for profiles since then. I'll have to figure out what Facebook changed and update the code to be compatible for both versions. 

Thanks for your suggestion, let me see if I can build that in while maintaining backwards compatibility (in case folks have old versions of downloaded profiles). Will let you know.

**Comment by jcontini** [comment]
Hey @maxrob27, I was able to update the Xpath queries to be compatible with Facebook's latest templates (as well as the older ones). Can you try again?

**Comment by jcontini** [comment]
@maxrob27 by the way, you don't have to re-download the facebook files. Just do this:

1. Delete the `profiles.json` file in `/db` (but not the profiles folder!)
2. Run `git pull` to pull the latest version of the script
3. Run `python make.py --parse` to recreate `profiles.json` properly

Alternative you can skip #3 and the script will automatically do it with all of your downloaded files on the next run (eg so you might have 90 instead of 45 profiles downloaded)

**Comment by maxrob27** [comment]
Hi again, I have made it the map! This is excellent, thanks again for the help. I'm just modifying the code a little so I can manually add anyone without a 'downloaded' location so hopefully it'll be even more complete! Thanks again for your help

**Comment by jcontini** [comment]
Awesome! I was thinking of pushing an update so that the script would use [SQLite](https://sqlitebrowser.org/) instead of JSON. Might do that within the next week, if you want to hold off so you can edit easier from a DB GUI interface.

**Comment by maxrob27** [comment]
I will keep an eye out for that. For now though, what i've done seems to work. It might be rather basic but it does the job.

**Comment by jcontini** [comment]
Awesome, glad to hear it's working for you!
